Error 2024-11-19 11:06:09 : invalid literal for int() with base 10: 'g'
Traceback (most recent call last):
  File "C:\Users\konsh\Documents\GitHub\Leviathan\main.py", line 37, in <module>
    asyncio.run(main())
  File "C:\Program Files\CastomProgramingFile\Python\PyhthonMain\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\CastomProgramingFile\Python\PyhthonMain\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\CastomProgramingFile\Python\PyhthonMain\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\konsh\Documents\GitHub\Leviathan\main.py", line 20, in main
    i= int('g')
       ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'g'



Error 2024-11-19 11:06:14 : invalid literal for int() with base 10: 'g'
Traceback (most recent call last):
  File "C:\Users\konsh\Documents\GitHub\Leviathan\main.py", line 37, in <module>
    asyncio.run(main())
  File "C:\Program Files\CastomProgramingFile\Python\PyhthonMain\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\CastomProgramingFile\Python\PyhthonMain\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\CastomProgramingFile\Python\PyhthonMain\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\konsh\Documents\GitHub\Leviathan\main.py", line 20, in main
    i= int('g')
       ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'g'



Error 2024-11-19 11:06:19 : invalid literal for int() with base 10: 'g'
Traceback (most recent call last):
  File "C:\Users\konsh\Documents\GitHub\Leviathan\main.py", line 37, in <module>
    asyncio.run(main())
  File "C:\Program Files\CastomProgramingFile\Python\PyhthonMain\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\CastomProgramingFile\Python\PyhthonMain\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\CastomProgramingFile\Python\PyhthonMain\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\konsh\Documents\GitHub\Leviathan\main.py", line 20, in main
    i= int('g')
       ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'g'



